<?php

$paragraphs = [
  "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, aliquid quo. Mollitia nisi quas ipsum quo soluta fuga quia nostrum, pariatur corrupti architecto laudantium harum, ducimus, voluptatibus facilis nemo impedit sunt labore at sint recusandae. Iusto praesentium porro eum exercitationem possimus earum dignissimos, doloremque error impedit aut fugiat illum quasi molestias, ut velit incidunt enim nam distinctio laudantium facere? Officia sed error cumque, vel distinctio minima harum dignissimos quisquam sequi amet voluptatibus eaque ipsam deleniti quam aut magnam rerum ullam aliquid? Provident necessitatibus repellendus totam veniam assumenda cupiditate expedita, beatae laborum fugiat doloremque, repudiandae, fugit tempora veritatis eius neque magni!",
  "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, aliquid quo. Mollitia nisi quas ipsum quo soluta fuga quia nostrum, pariatur corrupti architecto laudantium harum, ducimus, voluptatibus facilis nemo impedit sunt labore at sint recusandae. Iusto praesentium porro eum exercitationem possimus earum dignissimos, doloremque error impedit aut fugiat illum quasi molestias, ut velit incidunt enim nam distinctio laudantium facere? Officia sed error cumque, vel distinctio minima harum dignissimos quisquam sequi amet voluptatibus eaque ipsam deleniti quam aut magnam rerum ullam aliquid? Provident necessitatibus repellendus totam veniam assumenda cupiditate expedita, beatae laborum fugiat doloremque, repudiandae, fugit tempora veritatis eius neque magni!",
  "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, aliquid quo. Mollitia nisi quas ipsum quo soluta fuga quia nostrum, pariatur corrupti architecto laudantium harum, ducimus, voluptatibus facilis nemo impedit sunt labore at sint recusandae. Iusto praesentium porro eum exercitationem possimus earum dignissimos, doloremque error impedit aut fugiat illum quasi molestias, ut velit incidunt enim nam distinctio laudantium facere? Officia sed error cumque, vel distinctio minima harum dignissimos quisquam sequi amet voluptatibus eaque ipsam deleniti quam aut magnam rerum ullam aliquid? Provident necessitatibus repellendus totam veniam assumenda cupiditate expedita, beatae laborum fugiat doloremque, repudiandae, fugit tempora veritatis eius neque magni!",
];

?>
